os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9
before_install:
  - rvm install ruby-2.4.2
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - swiftenv install 4.0 || true
  - bundle install --without=documentation
before_script:
  - bundle exec danger
script:
  - set -o pipefail
  - swift test